name: ci react

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/react/**'
  pull_request:   
    branches:
        - main
    paths:
      - 'frontend/react/**'      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true        

jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Run Tests for React
    uses: ./.github/workflows/test.yml
    with:
      microservice: react
    secrets: inherit

  check-infra:
    uses: ./.github/workflows/check-infra.yml   
    secrets: inherit
  
  build:
    needs: [check-infra, test]
    if: github.event_name == 'push' && needs.check-infra.outputs.infra-available == 'true'
    name: Build React Docker Image
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/build-and-push.yml
    with:
      microservice: react
    secrets: inherit

  deploy:
    needs: [check-infra, build]
    if: github.event_name == 'push' && needs.check-infra.outputs.infra-available == 'true'
    uses: ./.github/workflows/deploy-jobs.yml
    with:
      microservice: react
      image_tag: latest
    secrets: inherit  
